// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/chat.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	v1/chat.proto

It has these top-level messages:
	ChatMessage
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage struct {
	Id     int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type   int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Domain string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	From   string `protobuf:"bytes,4,opt,name=from" json:"from,omitempty"`
	To     string `protobuf:"bytes,5,opt,name=to" json:"to,omitempty"`
	Msg    string `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ChatMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ChatMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChatMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "v1.ChatMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chat service

type ChatClient interface {
	OnMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_OnMessageClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) OnMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_OnMessageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/v1.Chat/OnMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatOnMessageClient{stream}
	return x, nil
}

type Chat_OnMessageClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatOnMessageClient struct {
	grpc.ClientStream
}

func (x *chatOnMessageClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatOnMessageClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chat service

type ChatServer interface {
	OnMessage(Chat_OnMessageServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_OnMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).OnMessage(&chatOnMessageServer{stream})
}

type Chat_OnMessageServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatOnMessageServer struct {
	grpc.ServerStream
}

func (x *chatOnMessageServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatOnMessageServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnMessage",
			Handler:       _Chat_OnMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/chat.proto",
}

func init() { proto.RegisterFile("v1/chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x33, 0xd4, 0x4f,
	0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x54, 0xaa, 0xe7,
	0xe2, 0x76, 0xce, 0x48, 0x2c, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0xe2, 0xe3, 0x62,
	0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62,
	0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0xc4, 0xb8,
	0xd8, 0x52, 0xf2, 0x73, 0x13, 0x33, 0xf3, 0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c,
	0x90, 0xda, 0xb4, 0xa2, 0xfc, 0x5c, 0x09, 0x16, 0xb0, 0x28, 0x98, 0x0d, 0x32, 0xaf, 0x24, 0x5f,
	0x82, 0x15, 0x2c, 0xc2, 0x54, 0x92, 0x2f, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0x06,
	0x16, 0x00, 0x31, 0x8d, 0xac, 0xb9, 0x58, 0x40, 0x0e, 0x10, 0x32, 0xe6, 0xe2, 0xf4, 0xcf, 0x83,
	0x39, 0x83, 0x5f, 0xaf, 0xcc, 0x50, 0x0f, 0xc9, 0x5d, 0x52, 0xe8, 0x02, 0x4a, 0x0c, 0x1a, 0x8c,
	0x06, 0x8c, 0x49, 0x6c, 0x60, 0x8f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xde, 0x1e,
	0x16, 0xd9, 0x00, 0x00, 0x00,
}
